# Dockerfile generated by DevOpsArk

# Use a minimal base image; update as needed (e.g., ubuntu:latest)
FROM ubuntu:latest

# Set environment variables for noninteractive installs
ENV DEBIAN_FRONTEND=noninteractive

# Install essential utilities (curl, wget, git)
RUN apt-get update && \
    apt-get install -y \
        curl \
        wget \
        git \
        ca-certificates \
        build-essential \
        && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy application source code (placeholder)
# COPY . /app

# Expose default port (update as required)
EXPOSE 8080

# Default command (update to run your application)
CMD ["bash"]